apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: mldeploymentautoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mldeployment
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - resource:
        name: cpu
        targetAverageUtilization: 50
      type: Resource
  resources:
    requests:
      cpu: "200m"  # Set your desired CPU request value
    limits:
      cpu: "500m"  # Set your desired CPU limit value
