name: ci

on: [workflow_dispatch]

jobs:
  docker:

    runs-on: ubuntu-latest
    steps:
      - name: Generate Timestamp
        id: timestamp
        run: echo "::set-output name=TIMESTAMP::$(date +'%Y%m%d%H%M%S')"
        
      - name: Checkout
        uses: actions/checkout@v3
          
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: quadribello/ml_app:latest, quadribello/ml_app:${{ steps.timestamp.outputs.TIMESTAMP }}
